name: it_fox_test
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_launcher_icons: ^0.13.0
  get_it: ^7.2.0
  flutter_secure_storage: ^8.0.0
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  rxdart: ^0.27.7
  retrofit: ^4.0.1
  hive: ^2.2.3
  dio: ^5.1.1
  freezed: ^2.3.2
  location: ^4.4.0
  path_provider: ^2.0.14
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  retrofit_generator: ^6.0.0+1
  freezed_annotation: ^2.2.0
  hive_generator: ^2.0.0

flutter_icons:
  android: "app_icon"
  ios: true
  image_path: "assets/app-icon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
