// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUFeyP2SQ5AXIXCf5vDsH3GvyzaYfSQok',
    appId: '1:848462754126:web:78ca5bf3a685d735806e1f',
    messagingSenderId: '848462754126',
    projectId: 'itfox-test',
    authDomain: 'itfox-test.firebaseapp.com',
    storageBucket: 'itfox-test.appspot.com',
    measurementId: 'G-7LCS5RYYX5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwuoR3O7yWIdXFwExcMEMEJ1XEfoV48oQ',
    appId: '1:848462754126:android:563ffbc3d6faff8d806e1f',
    messagingSenderId: '848462754126',
    projectId: 'itfox-test',
    storageBucket: 'itfox-test.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwXM0pxNgYn5wPnxUCwXdW2HKbvq50BqQ',
    appId: '1:848462754126:ios:bb13757555bb80e7806e1f',
    messagingSenderId: '848462754126',
    projectId: 'itfox-test',
    storageBucket: 'itfox-test.appspot.com',
    iosClientId: '848462754126-o86emfps0ehjsh1fumlcm183mnbd0642.apps.googleusercontent.com',
    iosBundleId: 'com.example.itFoxTest.dev',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwXM0pxNgYn5wPnxUCwXdW2HKbvq50BqQ',
    appId: '1:848462754126:ios:0593eade21145f3d806e1f',
    messagingSenderId: '848462754126',
    projectId: 'itfox-test',
    storageBucket: 'itfox-test.appspot.com',
    iosClientId: '848462754126-vh2cev1f7khkrvn8g9hv3mmenrqgchdc.apps.googleusercontent.com',
    iosBundleId: 'com.example.itFoxTest',
  );
}
